### PR TITLE
Update for GHC 8.6 (fixes #13)

### LINKED ISSUE #13: Build failure with GHC-8.6 and containers-0.6
~~~~
Building     enummapset-0.5.2.2
Failed to install enummapset-0.5.2.2
Build log ( ~/.cabal/logs/ghc-8.6.0.20180823/enummapset-0.5.2.2-2u0xauM3JVBCyceeGTpYwG.log ):
cabal: Entering directory '/tmp/cabal-tmp-26260/enummapset-0.5.2.2'
Configuring enummapset-0.5.2.2...
Preprocessing library for enummapset-0.5.2.2..
Building library for enummapset-0.5.2.2..
[1 of 5] Compiling Data.EnumSet     ( Data/EnumSet.hs, dist/build/Data/EnumSet.o )
[2 of 5] Compiling Data.EnumMap.Base ( Data/EnumMap/Base.hs, dist/build/Data/EnumMap/Base.o )
[3 of 5] Compiling Data.EnumMap.Strict ( Data/EnumMap/Strict.hs, dist/build/Data/EnumMap/Strict.o )
[4 of 5] Compiling Data.EnumMap.Lazy ( Data/EnumMap/Lazy.hs, dist/build/Data/EnumMap/Lazy.o )
[5 of 5] Compiling Data.EnumMap     ( Data/EnumMap.hs, dist/build/Data/EnumMap.o )

Data/EnumMap.hs:30:31: error:
    • Data.IntMap.insertWith' is gone. Use Data.IntMap.Strict.insertWith.
    • In the first argument of ‘(.)’, namely
        ‘I.insertWith' f (fromEnum k) x’
      In the second argument of ‘(.)’, namely
        ‘I.insertWith' f (fromEnum k) x . unWrap’
      In the expression:
        EnumMap . I.insertWith' f (fromEnum k) x . unWrap
   |
30 | insertWith' f k x = EnumMap . I.insertWith' f (fromEnum k) x . unWrap
   |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Data/EnumMap.hs:35:13: error:
    • Data.IntMap.insertWithKey' is gone. Use Data.IntMap.Strict.insertWithKey.
    • In the first argument of ‘(.)’, namely
        ‘I.insertWithKey' (f . toEnum) (fromEnum k) x’
      In the second argument of ‘(.)’, namely
        ‘I.insertWithKey' (f . toEnum) (fromEnum k) x . unWrap’
      In the expression:
        EnumMap . I.insertWithKey' (f . toEnum) (fromEnum k) x . unWrap
   |
35 |   EnumMap . I.insertWithKey' (f . toEnum) (fromEnum k) x . unWrap
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Data/EnumMap.hs:38:12: error:
    • Data.IntMap.fold' is gone. Use Data.IntMap.foldr or Prelude.foldr.
    • In the first argument of ‘(.)’, namely ‘I.fold f a’
      In the expression: I.fold f a . unWrap
      In an equation for ‘fold’: fold f a = I.fold f a . unWrap
   |
38 | fold f a = I.fold f a . unWrap
   |            ^^^^^^^^^^

Data/EnumMap.hs:41:19: error:
    • Data.IntMap.foldWithKey is gone. Use foldrWithKey.
    • In the first argument of ‘(.)’, namely
        ‘I.foldWithKey (f . toEnum) a’
      In the expression: I.foldWithKey (f . toEnum) a . unWrap
      In an equation for ‘foldWithKey’:
          foldWithKey f a = I.foldWithKey (f . toEnum) a . unWrap
   |
41 | foldWithKey f a = I.foldWithKey (f . toEnum) a . unWrap
   |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Leaving directory '/tmp/cabal-tmp-26260/enummapset-0.5.2.2'
~~~~

### PR DESCRIPTION
**Pull request by Mikolaj**
Compiles fine with GHC 8.6.3, 8.0.2 and 7.10.3. Tested quite a bit on GHC 8.6.3.

### CODE REVIEW

**Comment by Mikolaj** [comment]
ping @michalt: could you merge this PR and release on Hackage? I offer my help: I will take responsibility for any fallout from this PR and I may also manage the release process if that's helpful (you'd need to give me github and Hackage permissions). Thank you!

File: Data/EnumMap.hs [hunk 1]
```diff
@@ -1,3 +1,5 @@
+{-# LANGUAGE CPP, DataKinds, FlexibleContexts, FlexibleInstances,
```
Comment (michalt) [inline Data/EnumMap.hs]: Could I ask you to add a comment that all these extensions are only needed for `Whoops`? Thanks!
